### ISSUE TITLE
error when i try to launch the application

### ISSUE THREAD

**Issue by masterzion** [juancarlospaco/pyvoicechanger#3]
```python
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=8, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=b'\x00_pyvoicechanger__lock'>. 
Traceback (most recent call last):
  File "<stdin>", line 201, in <module>
  File "<stdin>", line 187, in main
  File "/usr/local/lib/python3.5/dist-packages/anglerfish/set_desktop_launcher.py", line 17, in set_desktop_launcher
    if not isinstance(str, app) or not isinstance(str, desktop_file_content):
TypeError: isinstance() arg 2 must be a type or tuple of types
Compressed Unused Old Rotated Python Logs since: ~2017-07-26 19:10:16+02:00. 
```

**Comment by ITwrx** [comment]
i don't know if my input is useful, but me too. :)

pyvoicechanger.py
Testing Terminal Colors...
Unix SysLog Server trying to Log to SysLog: /dev/log 
Logger created with Log file at: /tmp/pyvoicechanger.log. 
PyVoiceChanger.1.0.0https://github.com/juancarlospaco/pyvoicechanger#pyvoicechanger 
Python 3.6.2 on Linux-4.12.2-1-hardened-x86_64-with-arch. 
STDIN Encoding: UTF-8. 
STDERR Encoding: UTF-8. 
STDOUT Encoding:UTF-8 
Default Encoding: utf-8. 
FileSystem Encoding: utf-8. 
PYTHONIOENCODING Encoding: None. 
Process Name set to: pyvoicechanger. 
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=8, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=b'\x00_pyvoicechanger__lock'>. 
Traceback (most recent call last):
  File "/usr/bin/pyvoicechanger.py", line 201, in <module>
    main()
  File "/usr/bin/pyvoicechanger.py", line 187, in main
    set_desktop_launcher("pyvoicechanger", desktop_file_content)
  File "/usr/lib/python3.6/site-packages/anglerfish-2.5.0-py3.6.egg/anglerfish/set_desktop_launcher.py", line 17, in set_desktop_launcher
TypeError: isinstance() arg 2 must be a type or tuple of types
Compressed Unused Old Rotated Python Logs since: ~2017-07-26 16:39:35-05:00.

**Comment by GNUGradyn** [comment]
Same issue
`Testing Terminal Colors...
                                                                                 
                                                                                 
                                                                                  

Unix SysLog Server trying to Log to SysLog: /dev/log 
Logger created with Log file at: /tmp/pyvoicechanger.log. 
PyVoiceChanger.1.0.0https://github.com/juancarlospaco/pyvoicechanger#pyvoicechanger 
Python 3.6.1 on Linux-4.11.2-1-ARCH-x86_64-with-arch. 
STDIN Encoding: UTF-8. 
STDERR Encoding: UTF-8. 
STDOUT Encoding:UTF-8 
Default Encoding: utf-8. 
FileSystem Encoding: utf-8. 
PYTHONIOENCODING Encoding: None. 
Process Name set to: pyvoicechanger. 
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=8, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=b'\x00_pyvoicechanger__lock'>. 
Traceback (most recent call last):
  File "pyvoicechanger.py", line 201, in <module>
    main()
  File "pyvoicechanger.py", line 187, in main
    set_desktop_launcher("pyvoicechanger", desktop_file_content)
  File "/usr/lib/python3.6/site-packages/anglerfish/set_desktop_launcher.py", line 17, in set_desktop_launcher
    if not isinstance(str, app) or not isinstance(str, desktop_file_content):
TypeError: isinstance() arg 2 must be a type or tuple of types
Compressed Unused Old Rotated Python Logs since: ~2017-08-12 14:22:22-06:00. 
() 
`

**Comment by juancarlospaco** [comment]
WIP Fix for this is on active Development, we hope to have it ASAP, but its happening somewhere else:
https://github.com/juancarlospaco/anglerfish#angler

**Comment by DoxingMethod** [comment]
Same issue still.

**Comment by juancarlospaco** [comment]
Fixed on Master.
